# Generated by Django 5.2.15 on 2026-06-10 13:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Munka neve')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Ügyfél neve')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Helyszín')),
                ('estimated_hours', models.DecimalField(decimal_places=1, help_text='A munka elvégzéséhez szükséges becsült idő órában.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))], verbose_name='Becsült munkaóra')),
                ('remaining_hours', models.DecimalField(decimal_places=1, default=0, help_text='Automatikusan számolódik a beosztás alapján.', max_digits=7, verbose_name='Hátralévő munkaóra')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Határidő')),
                ('earliest_start_date', models.DateField(blank=True, null=True, verbose_name='Legkorábbi kezdés')),
                ('priority', models.CharField(choices=[('low', 'Alacsony'), ('medium', 'Normál'), ('high', 'Magas'), ('urgent', 'Sürgős')], default='medium', max_length=10, verbose_name='Prioritás')),
                ('status', models.CharField(choices=[('draft', 'Vázlat'), ('planned', 'Beosztva'), ('in_progress', 'Folyamatban'), ('completed', 'Kész'), ('cancelled', 'Törölve'), ('overdue', 'Késésben')], default='draft', max_length=20, verbose_name='Státusz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
            ],
            options={
                'verbose_name': 'Munka',
                'verbose_name_plural': 'Munkák',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workday_start', models.TimeField(default='08:00', verbose_name='Munkanap kezdete')),
                ('workday_end', models.TimeField(default='16:00', verbose_name='Munkanap vége')),
                ('lunch_break_start', models.TimeField(default='12:00', verbose_name='Ebédszünet kezdete')),
                ('lunch_break_end', models.TimeField(default='12:30', verbose_name='Ebédszünet vége')),
                ('default_daily_hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('16'))], verbose_name='Alap napi munkaóra')),
                ('max_daily_hours', models.DecimalField(decimal_places=1, default=10.0, help_text='Ennél többet egy napra nem oszt be a rendszer.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('16'))], verbose_name='Maximum napi munkaóra')),
                ('min_schedule_block_hours', models.DecimalField(decimal_places=1, default=0.5, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))], verbose_name='Minimum beosztható blokk (óra)')),
                ('allow_weekend', models.BooleanField(default=False, verbose_name='Hétvégi munka engedélyezése')),
                ('mon_active', models.BooleanField(default=True, verbose_name='Hétfő')),
                ('tue_active', models.BooleanField(default=True, verbose_name='Kedd')),
                ('wed_active', models.BooleanField(default=True, verbose_name='Szerda')),
                ('thu_active', models.BooleanField(default=True, verbose_name='Csütörtök')),
                ('fri_active', models.BooleanField(default=True, verbose_name='Péntek')),
                ('sat_active', models.BooleanField(default=False, verbose_name='Szombat')),
                ('sun_active', models.BooleanField(default=False, verbose_name='Vasárnap')),
            ],
            options={
                'verbose_name': 'Beállítás',
                'verbose_name_plural': 'Beállítások',
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Megnevezés')),
                ('start_datetime', models.DateTimeField(verbose_name='Kezdés')),
                ('end_datetime', models.DateTimeField(verbose_name='Befejezés')),
                ('reason', models.CharField(blank=True, help_text='Pl. szabadság, ünnepnap, esőnap, magánprogram', max_length=200, verbose_name='Ok')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
            ],
            options={
                'verbose_name': 'Tiltott időszak',
                'verbose_name_plural': 'Tiltott időszakok',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Kezdés')),
                ('end_datetime', models.DateTimeField(verbose_name='Befejezés')),
                ('hours', models.DecimalField(decimal_places=1, help_text='A blokk hossza órában.', max_digits=5, verbose_name='Óra')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Megjegyzés')),
                ('is_auto_scheduled', models.BooleanField(default=False, verbose_name='Automatikus beosztás')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='naptar.job', verbose_name='Munka')),
            ],
            options={
                'verbose_name': 'Beosztás',
                'verbose_name_plural': 'Beosztások',
                'ordering': ['start_datetime'],
            },
        ),
    ]
